server:
  port: 10002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renchehui?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 950421
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml
myname: zhangsan123
